[exercises]
order = [
  "syntax/syntax01",
  "syntax/syntax02",
  "syntax/syntax03",
  "syntax/syntax04",
  "syntax/syntax05",
  "operations/operations00",
  "operations/operations01",
  "operations/operations02",
  "operations/operations03",
  "strings/strings00",
  "strings/strings01",
  "implicit_arguments/implicit_arguments01",
  "implicit_arguments/implicit_arguments02",
  "implicit_arguments/implicit_arguments03",
  "recursions/recursion01",
  "recursions/array01",
  "recursions/array02",
  "recursions/array03",
  "recursions/array04",
  "recursions/collatz_sequence",
  "registers/registers00",
  "registers/registers01",
  "registers/registers02",
  "registers/registers03",
  "registers/registers04",
  "revoked_references/revoked_references01",
  "builtins/bitwise",
  "tricks/no_conditionals",
  "tricks/assert_bool",
  "tricks/inline_if",
  "hints/hints00",
  "hints/hints01",
]

[hints]
